// Require User model.
const { Album } = require('../models');
// Data to be seeded by bulk creation.
const albumData = [
  {
    title: "Thriller",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689879390/TuneStack/lfzde3vxerxitvi6taxa.png",
    extension_url: "https://www.michaeljackson.com/video/thriller-video-2/",
    artist: "Michael Jackson",
    year: "1982",
    genre: "Pop",
    description: "Thriller is the sixth studio album by American singer Michael Jackson",
    creator_id: "3",
  },
  {
    title: "Abbey Road",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689881309/TuneStack/vxllubujrjbvxmf21gfp.jpg",
    extension_url: "https://www.tripadvisor.com/Attraction_Review-g186338-d190102-Reviews-Abbey_Road-London_England.html",
    artist: "The Beatles",
    year: "1969",
    genre: "Rock",
    description: "Abbey Road is the eleventh studio album by English rock band the Beatles",
    creator_id: "1",
  },
  {
    title: "The Dark Side of the Moon",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689881412/TuneStack/Dark_Side_of_the_Moon_edddzf.png",
    extension_url: "https://www.amazon.com/Dark-Side-Moon-Pink-Floyd/dp/B000002U82",
    artist: "Pink Floyd",
    year: "1973",
    genre: "Progressive Rock",
    description: "The Dark Side of the Moon is the eighth studio album by English rock band Pink Floyd",
    creator_id: "2",
  },
  {
    title: "Back in Black",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882165/TuneStack/440px-ACDC_Back_in_Black_cover.svg_phzry6.png",
    extension_url: "https://genius.com/Ac-dc-back-in-black-lyrics",
    artist: "AC/DC",
    year: "1980",
    genre: "Hard Rock",
    description: "Back in Black is the seventh studio album by Australian rock band AC/DC",
    creator_id: "5",
  },
  {
    title: "Hotel California",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882270/TuneStack/https_3A_2F_2Fimages.genius.com_2F6c7e025561819a4af1476af223c1a7f8.600x600x1_yowh68.jpg",
    extension_url: "https://genius.com/Eagles-hotel-california-lyrics",
    artist: "Eagles",
    year: "1976",
    genre: "Rock",
    description: "Hotel California is the fifth studio album by American rock band Eagles",
    creator_id: "4",
  },
  {
    title: "Nevermind",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882338/TuneStack/NirvanaNevermindalbumcover_hqepzx.jpg",
    extension_url: "https://www.nirvana.com/album/nevermind/",
    artist: "Nirvana",
    year: "1991",
    genre: "Grunge",
    description: "Nevermind is the second studio album by American rock band Nirvana",
    creator_id: "2",
  },
  {
    title: "The Joshua Tree",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882419/TuneStack/The_Joshua_Tree_vprup9.png",
    extension_url: "https://www.amazon.com/Joshua-Tree-U2/dp/B000001FS3",
    artist: "U2",
    year: "1987",
    genre: "Rock",
    description: "The Joshua Tree is the fifth studio album by Irish rock band U2",
    creator_id: "3",
  },
  {
    title: "Rumours",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882508/TuneStack/FMacRumours_swqgsk.png",
    extension_url: "https://www.allmusic.com/album/rumours-mw0000193833",
    artist: "Fleetwood Mac",
    year: "1977",
    genre: "Rock",
    description: "Rumours is the eleventh studio album by British-American rock band Fleetwood Mac",
    creator_id: "1",
  },
  {
    title: "Born to Run",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882623/TuneStack/Born_to_Run__28Front_Cover_29_lef2qe.jpg",
    extension_url: "https://en.wikipedia.org/wiki/Born_to_Run",
    artist: "Bruce Springsteen",
    year: "1975",
    genre: "Rock",
    description: "Born to Run is the third studio album by American singer-songwriter Bruce Springsteen",
    creator_id: "5",
  },
  {
    title: "Led Zeppelin IV",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882723/TuneStack/Led_Zeppelin_-_Led_Zeppelin_IV_ezkor4.jpg",
    extension_url: "https://www.discogs.com/master/4300-Led-Zeppelin-Untitled-",
    artist: "Led Zeppelin",
    year: "1971",
    genre: "Rock",
    description: "Led Zeppelin IV is the fourth studio album by English rock band Led Zeppelin",
    creator_id: "2",
  },
  {
    title: "Sgt. Pepper's Lonely Hearts Club Band",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882797/TuneStack/Sgt._Pepper_27s_Lonely_Hearts_Club_Band_qd8y2p.jpg",
    extension_url: "https://www.thebeatles.com/sgt-peppers-lonely-hearts-club-band-0",
    artist: "The Beatles",
    year: "1967",
    genre: "Rock",
    description: "Sgt. Pepper's Lonely Hearts Club Band is the eighth studio album by The Beatles",
    creator_id: "2",
  },
  {
    title: "The Wall",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689882859/TuneStack/PinkFloydWallCoverOriginalNoText_fmjr3m.jpg",
    extension_url: "https://open.spotify.com/album/5Dbax7G8SWrP9xyzkOvy2F",
    artist: "Pink Floyd",
    year: "1979",
    genre: "Progressive Rock",
    description: "The Wall is the eleventh studio album by English rock band Pink Floyd",
    creator_id: "5",
  },
  {
    title: "Blackout",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883077/TuneStack/Blackout__28Scorpions_album_-_cover_art_29_r7udo8.png",
    extension_url: "https://www.discogs.com/master/29283-Scorpions-Blackout",
    artist: "Scorpions",
    year: "1982",
    genre: "Hard Rock",
    description: "Blackout is the eighth studio album by German rock band Scorpions",
    creator_id: "1",
  },
  {
    title: "Appetite for Destruction",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883147/TuneStack/GunsnRosesAppetiteforDestructionalbumcover_oy1w5k.jpg",
    extension_url: "https://www.amazon.com/Appetite-Destruction-Guns-N-Roses/dp/B000000OQF",
    artist: "Guns N' Roses",
    year: "1987",
    genre: "Hard Rock",
    description: "Appetite for Destruction is the debut studio album by Guns N' Roses",
    creator_id: "3",
  },
  {
    title: "Highway to Hell",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883239/TuneStack/Acdc_Highway_to_Hell_nqe3s6.jpg",
    extension_url: "https://genius.com/Ac-dc-highway-to-hell-lyrics",
    artist: "AC/DC",
    year: "1979",
    genre: "Hard Rock",
    description: "Highway to Hell is the sixth studio album by Australian rock band AC/DC",
    creator_id: "3",
  },
  {
    title: "Bad",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883318/TuneStack/Michael_Jackson_-_Bad_mnq7jy.png",
    extension_url: "https://www.michaeljackson.com/music/bad-1/",
    artist: "Michael Jackson",
    year: "1987",
    genre: "Pop",
    description: "Bad is the seventh studio album by American singer Michael Jackson",
    creator_id: "5",
  },
  {
    title: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883382/TuneStack/ZiggyStardust_b62mtc.jpg",
    extension_url: "https://www.allmusic.com/album/the-rise-and-fall-of-ziggy-stardust-and-the-spiders-from-mars-mw0000626129",
    artist: "David Bowie",
    year: "1972",
    genre: "Rock",
    description: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars is the fifth studio album by David Bowie",
    creator_id: "4",
  },
  {
    title: "Ride the Lightning",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883462/TuneStack/Ridetl_vjwriu.png",
    extension_url: "https://www.metallica.com/songs/ride-the-lightning.html",
    artist: "Metallica",
    year: "1984",
    genre: "Thrash Metal",
    description: "Ride the Lightning is the second studio album by American heavy metal band Metallica",
    creator_id: "2",
  },
  {
    title: "Purple Rain",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883544/TuneStack/Princepurplerain_td0jeb.jpg",
    extension_url: "https://discography.prince.com/albums/purple-rain",
    artist: "Prince",
    year: "1984",
    genre: "Pop, Rock, R&B",
    description: "Purple Rain is the sixth studio album by American recording artist Prince",
    creator_id: "1",
  },
  {
    title: "The Doors",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883654/TuneStack/TheDoorsTheDoorsalbumcover_qtekzv.jpg",
    extension_url: "https://thedoors.com/",
    artist: "The Doors",
    year: "1967",
    genre: "Psychedelic Rock",
    description: "The Doors is the debut album by American rock band the Doors",
    creator_id: "5",
  },
  {
    title: "Breakfast in America",
    artist: "Supertramp",
    year: "1979",
    genre: "Progressive Rock",
    description: "Breakfast in America is the sixth studio album by Supertramp, released in 1979.",
    cloudinary_url: "https://res.cloudinary.com/dx7bgdfut/image/upload/v1689883952/TuneStack/Supertramp_-_Breakfast_in_America_eosezz.jpg",
    extension_url: "https://genius.com/Supertramp-breakfast-in-america-lyrics",
    creator_id: "4"
  },
];
// Function that will seed all data to schema at once.
const seedAlbums = () => Album.bulkCreate(albumData);
// Export function so that it can be used elsewhere.
module.exports = seedAlbums;